marcin_site:
    resource: "@MarcinSiteBundle/Resources/config/routing.yml"
    prefix:   /

common_user:
    resource: "@CommonUserBundle/Resources/config/routing.yml"
    prefix:   /

marcin_admin:
    resource: "@MarcinAdminBundle/Resources/config/routing.yml"
    prefix:   /panel