common_user_login:
    resource: "@CommonUserBundle/Controller/LoginController.php"
    type: annotation
    prefix: /login
    #path:     /
    #defaults: { _controller: CommonUserBundle:Default:index }
    
common_user_index:
    resource: "@CommonUserBundle/Controller/LoginController.php"
    type: annotation
    prefix: /
    
_check_path:
    path: /login-check
    
_logout:
    path: /logout