services:
#    common_user.example:
#        class: Common\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  #  user_managers:
  #      class: Common\UserBundle\Manager\UserManagers
  #      arguments: [@doctrine, @router, @templating, @security.encoder_factory]
  
  