services:
#    common_user.example:
#        class: Common\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    user_manager:
        class: Common\UserBundle\Manager\UserManager
        arguments: [@doctrine, @router, @templating, @security.encoder_factory]